### PR TITLE
Fix layout shifting using `panelaspect` property

### LINKED ISSUE #677: Panels need to fill the space they are supposed to prior to images loading
We want to maintain the shape of the grid even if images haven't loaded. In this screenshot the panels that haven't loaded don't take up the screen space that they should.

image

### PR DESCRIPTION
**Pull request by jefferymills**

### CODE REVIEW

File: src/components/Panel/PanelGraphic.tsx [hunk 1]
```diff
@@ -5,13 +5,18 @@ interface PanelGraphicProps {
...
-  <div className={styles.panelGraphic}>
+const PanelGraphic: React.FC<PanelGraphicProps> = ({ type, src, alt, aspectRatio }) => (
+  <div className={styles.panelGraphic} style={{ aspectRatio }}>
     {type === 'iframe' && <iframe width="100%" height="100%" scrolling="no" src={src} title={alt} />}
     {type === 'img' && <img src={src} alt={alt} />}
   </div>
 );
 
+PanelGraphic.defaultProps = {
+  aspectRatio: undefined,
```
Comment (Incin) [inline src/components/Panel/PanelGraphic.tsx:19]: is there a way to do this without using defaultProps?

**Review by Incin — APPROVED** [review]
